# Generated by Django 3.1.4 on 2020-12-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('S', 'Sports'), ('T', 'Traveling'), ('F', 'Food')], max_length=10, null=True),
        ),
    ]
