# Generated by Django 3.1.4 on 2020-12-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201209_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Travel', 'Travel'), ('Food', 'Food')], max_length=10, null=True),
        ),
    ]
